json.ID expense.id
json.Amount expense.amount
json.Description expense.description
json.Category expense.category_id
json.Trip expense.trip_id
json.Photo expense.photo 
json.Date expense.date
json.activity expense.itinerary_id
json.Expense_type expense.expense_type